system:
  random_seed: 42
  device: "cuda" # "cpu", "auto", "cuda"

data:
  uci_id: 891 # dataset id
  val_size: 0.1
  test_size: 0.2

  # "under" -> 작은 샘플에 맞추기
  # "smote" -> 작은 샘플 생성하여 확장
  # "none" -> 아무 작업 X
  sampling_method: "smote"
  sampling_ratio: 1 # 비율 -> 작은 거 / 큰 거

  batch_size: 64
  num_workers: 2

model:
  # LR, DT, RF, IF, AE
  name: "AE"

  # AE
  lr: 0.001
  epochs: 50
  hidden_dim: 16

  # Machine Learning Params
  n_estimators: 100 # RF
  contamination: 0.15 # IF
  max_iter: 1000 # LR
  n_jobs: -1 # RF, IF

threshold:
  type: "F1-max" # Top-k or F1-max
  contamination: 0.15 # Top-k

scheduler:
  type: "ReduceLROnPlateau"
  params:
    patience: 3
    factor: 0.5
    min_lr: 1.0e-6
    mode: "max"
  monitor: "val_auprc"
  interval: "epoch"
  frequency: 1

logging:
  save_dir: "./outputs"
  save_top_k: 3
  monitor: "val_auprc" # val_auroc 도 고려
  mode: "max" # val_auroc -> max

# Wandb
wandb:
  team_name: "lkl4502-kookmin-university"
  project_name: "AI-Security-Project"
  experiment_name: "SMOTE-1-AE"
